version: '3.2'
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ../:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html/
networks:
  frontend:
  backend:
