version: '3.7'
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ../:/var/www/arango-importer/

  web:
    build: './nginx/'
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - ../:/var/www/arango-importer/
    networks:
      - frontend
      - backend

  arangodb:
    image: arangodb/arangodb:3.6
    networks:
      - backend
    ports:
      - '8529:8529'
    environment:
      - ARANGO_ROOT_PASSWORD=test05
networks:
  frontend:
  backend:
