version: '3.7'
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ../:/var/www/html/
  arangodb:
    image: arangodb/arangodb:latest
    networks:
      - backend
    ports:
      - '8529:8529'
    environment:
      - ARANGO_ROOT_PASSWORD=test05
  apache:
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html/
networks:
  frontend:
  backend:
